### ISSUE TITLE
Cant use it with NuxtJS

### ISSUE THREAD

**Issue by 1hakr** [morphatic/v-stripe-elements#1]
I'm trying to integrate this with my Nuxt project. I followed all the steps but it shows the following warning and doesnt display anything.

`[Vue warn]: Unknown custom element: <v-stripe-card> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

**Comment by morphatic** [comment]
Thank you for raising this issue. I had suspected that this component would not work with Nuxt (or any other SSR scenario), but I hadn't gotten around to testing it yet. This confirms my suspicion.

Here's the problem: [Stripe Elements](https://stripe.com/payments/elements) is specifically a **client-side** library designed to swap out a specified DOM element (usually a `div` or `input`) with an `iframe` **after** the page has loaded. 

If you're doing your rendering and processing on the **server-side** you should probably be using [`stripe-node`](https://github.com/stripe/stripe-node). In that case, you can just use Vuetify's standard `v-text-field` components to gather the card number, CVC, expiration date, etc. When your user submits the form, all of this data would get sent back to the server side for processing and verification. If you want the bells and whistles, like the card icon that updates in response to user typing in their card number, you would use the `prepend` or `prepend-inner` slot to add and update the icon shown.

When I first started working with Stripe, I was pretty confused by the existence of both Stripe Node, and Stripe Elements. Now it is clear to me why the two packages exist.

So, I don't think this package is going to work in your situation. Sorry!

I will update the documentation to make it clear that this component is not for use in SSR situations, like Nuxt.

**Comment by 1hakr** [comment]
But i dont want to use it on server side, i just want to use it after the page has loaded. Actually it's part of dialog which opens on certain user interaction. I basically wanted to use stripe elements but found your library. So will it not work on just client side in a nuxt app?

**Comment by morphatic** [comment]
So, I've never really used Nuxt before, but it appears that something like this might work. You'd need to use `v-stripe-elements` as a "plugin." So first, create a `v-stripe-elements.js` file in your `/plugins` folder that has the following content:

```js
// plugins/v-stripe-elements.js
import VStripeElements from 'v-stripe-elements'

Vue.use(VStripeElements)
```

Then in your main `nuxt.config.js` file, add the plugin to the `plugins` array like this:

```js
// nuxt.config.js
module.exports = {
  // ... your other config options ...
  plugins: [
    // ... other plugins you might have registered ... //
    { src: '~/plugins/v-stripe-elements', mode: 'client' }
  ]
}
```

This should make the `<v-stripe-card>` component available globally in your project, so you can just use it in your template wherever it appears.

**Comment by morphatic** [comment]
I was able to get it to work with Nuxt with the configuration described above. I had one issue which was that for some reason the styles were not loading. As a workaround, until I can get it to work properly, I just imported the styles from jsDelivr the same way I do in my CodePen demo. To do this:

```js
// nuxt.config.js
module.exports = {
  // ... other config ...
  head: {
    // ... other <head> items ...
    link: [
      // ... other <link> items ...
      { rel: 'stylesheet', type: 'text/css', href: 'https://cdn.jsdelivr.net/npm/v-stripe-elements@v1.2.0/dist/v-stripe-elements.min.css' }
    ]
  },
  // ... the rest of your config file ...
}
```

**Comment by 1hakr** [comment]
Got it working!
