### ISSUE TITLE
Option to reset

### ISSUE THREAD

**Issue by 1hakr** [morphatic/v-stripe-elements#16]
Currently there is not way clear the form, after there is a message and also to regenerate the token.

**Comment by morphatic** [comment]
@1hakr have you tried setting the `clearable` property on the element?

```html
<v-stripe-card
  v-model="token"
  :api-key="apiKey"
  :clearable="clearable"
></v-stripe-card>
```

This prop is inherited from `v-text-field`. If you clear the field and then re-enter the number, when you change the value it should re-generate the token.

**Comment by 1hakr** [comment]
Yes but the user has to click on the cross button to clear it. I'm talking about resetting it when the user opens the dialog again, it still shows previous entered fields and there is no way to clear it programatically.

**Comment by DLO33** [comment]
@1hakr I'm not sure if this way is the best way to clear the inputs but it works.
I'm doing this after submit, but you could do this when the dialog is opened . 

Add ref to the card
```
<v-stripe-card
        ref="stripeCard"
        v-model="stripeData"
        :api-key="stripeKey"
        :customStyle="stripeStyle"
        :hidePostalCode="true"
        clearable
      ></v-stripe-card>
```

call the clearableCallback function.
`this.$refs.stripeCard.clearableCallback();`

**Comment by 1hakr** [comment]
This works. Thanks @DLO33
