### ISSUE TITLE
How I made a Required validation with v-stripe-card

### ISSUE THREAD

**Issue by enpepolicy** [morphatic/v-stripe-elements#233]
Hey guys, I have been struggling some nights on making a v-form validatable required v-stripe-card. I found this way, and post it here if someone find's it usefull.

[VStripeCardField ](https://gist.github.com/enpepolicy/bbe6177e8595c5a1648efb6c878a38f2)

You should call the validate() function on parent component using ref.

**Comment by morphatic** [comment]
@enpepolicy, I realize it's been over 2 years since you posted this, but thank you for the contribution!!
